SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

SCORE_ASTEROID_BASE = 50

PLAYER_LIVES = 3
PLAYER_RESPAWN_INVULNERABILITY_SECONDS = 2.0

WEAPON_SINGLE = "single"
WEAPON_SPREAD = "spread"
WEAPON_RAPID = "rapid"
WEAPON_SPREAD_ANGLE = 15
WEAPON_RAPID_COOLDOWN_SECONDS = 0.1

POWERUP_RADIUS = 12
POWERUP_SPAWN_RATE_SECONDS = 5.0
POWERUP_LIFETIME_SECONDS = 8.0
SHIELD_DURATION_SECONDS = 5.0
SPEED_BOOST_DURATION_SECONDS = 5.0
SPEED_BOOST_MULTIPLIER = 1.8

BOMB_RADIUS = 8
BOMB_FUSE_SECONDS = 2.0
BOMB_BLAST_RADIUS = 120
BOMB_COOLDOWN_SECONDS = 3.0